name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: productive-box
        uses: maxam2017/productive-box@v1.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LOCALE: ko-KR
